- name: install clearwater-cassandra packets
  apt: name=clearwater-cassandra force=yes  state=present

- name: install homer packets
  apt: name=homer force=yes state=present

- name: install clearwater-config-manager
  apt: name=clearwater-config-manager force=yes state=present

- name: wait for etcd
  command: /usr/share/clearwater/clearwater-etcd/scripts/wait_for_etcd

- name: copy script
  template: src=ns.sh dest=/tmp/ns.sh owner=root group=root mode=0744

- name: exec ns.sh
  shell: /tmp/ns.sh
